title: Woodenday
description: Современный декор интерьера 3D панелями из дерева.
show_downloads: "true"
theme: jekyll-theme-minimal
lang: ru
shortcut_icon: /assets/img/logo.png
google_analytics: UA-134263384-1
